const mockUsers = [
  {
    id: '1',
    photoUrl: '/img/jack.png',
    role: 'Admin',
    team: 'Creative',
    email: 'jackj@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
    name: 'Jack Jackson',
  },
  {
    id: '2',
    photoUrl: '/img/victoria.png',
    role: 'Admin',
    team: 'Management',
    email: 'victoriaf@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
    name: 'Victoria Ferguson',
  },
  {
    id: '3',
    photoUrl: '/img/donna.png',
    role: 'Admin',
    team: 'Finance & Admin',
    email: 'donnah@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
    name: 'Donna Hicks',
  },
  {
    id: '4',
    photoUrl: '/img/mary.png',
    role: 'Employee',
    team: 'Creative',
    email: 'maryl@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
    name: 'Mary Long',
  },
  {
    id: '5',
    photoUrl: '/img/andy.png',
    role: 'Employee',
    team: 'Creative',
    email: 'andym@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
    name: 'Andy Mann',
  },
  {
    id: '6',
    role: 'Applicant',
    team: 'Development',
    email: 'luckytintinnz@gmail.com',
    address: 'Queen St CBD',
    city: 'Auckland',
    name: 'Giang Nguyen',
  }
];

export default mockUsers;