const mockUsers = [
  {
    id: '1',
    photoUrl: '/img/jack.png',
    firstName: 'Jack',
    lastName: 'Jackson',
    role: 'Admin',
    team: 'Creative',
    email: 'jackj@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
  },
  {
    id: '2',
    photoUrl: '/img/victoria.png',
    firstName: 'Victoria',
    lastName: 'Ferguson',
    role: 'Admin',
    team: 'Management',
    email: 'victoriaf@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
  },
  {
    id: '3',
    photoUrl: '/img/donna.png',
    firstName: 'Donna',
    lastName: 'Hicks',
    role: 'Admin',
    team: 'Finance & Admin',
    email: 'donnah@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
  },
  {
    id: '4',
    photoUrl: '/img/mary.png',
    firstName: 'Mary',
    lastName: 'Long',
    role: 'Employee',
    team: 'Creative',
    email: 'maryl@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
  },
  {
    id: '5',
    photoUrl: '/img/andy.png',
    firstName: 'Andy',
    lastName: 'Mann',
    role: 'Employee',
    team: 'Creative',
    email: 'andym@affinityid.co.nz',
    address: '307 Brant Road',
    city: 'Auckland',
  }
];

export default mockUsers;